import Head from 'next/head'
import { NavBar, Footer, Banner } from '../components'

export default function Home() {
	return (
		<div className='overflow-x-hidden'>
			<Head>
				<title>Green Chase</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<NavBar />
			<Banner />
			<Footer />
		</div>
	)
}
